### ISSUE TITLE
How to gracefully terminate a session, but not a connection

### ISSUE THREAD

**Issue by afrind** [ietf-wg-webtrans/draft-webtransport-http2#12]
It's possible that a WebTransport endpoint may wish to drain a session, such that the peer would know not to create new streams on that session, but existing sessions could complete before closing the session's stream.  We need something like GOAWAY, but scoped to a single session.

This is useful when there are multiple sessions (and possibly other HTTP traffic) multiplexed on a single connection, which are routed to different upstream servers.  If a single upstream server needs to restart (and gracefully drain), it would be nice to not have to drain all the sessions/traffic from the client's connection.

**Comment by ekinnear** [comment]
Could the Connect Stream be used for this (since it is 1:1 a session already and the lifetime is tied to that connect stream)? I guess we're already there a bit, but just resetting that stream loses the routing information you need to clean up, hence the need for something like GOAWAY, like you said. :)

**Comment by afrind** [comment]
I think we should let the design happen for H3 (https://github.com/ietf-wg-webtrans/draft-ietf-webtrans-http3/issues/27) and then translate that here.

**Comment by ekinnear** [comment]
Done with #26, closing the CONNECT stream kills the session, but you can have other CONNECT streams (and other sessions within them) that are entirely unaffected.
