### ISSUE TITLE
Coalescing effects on security

### ISSUE THREAD

**Issue by martinthomson** [ietf-wg-webtrans/draft-webtransport-http2#23]
The document claims that two sessions that share a connection as the result of coalescing might be mutually distrustful.  I don't think that this is correct.

At least from the client's perspective, the two origins can read the plaintext of the message sent to each other.  They are also able to exhaust the shared pool of available streams by making HTTP requests.   The degree to which WebTransport creates any additional risk here has to be minimal.  Yes, it becomes slightly easier to mount a resource exhaustion attack, but it is - at least from the perspective of the client - only self-inflicted.

It is also unclear here that any single scheme would be effective without clearer - and ideally deterministic - limits being set.  I'll open a separate issue on that.

**Comment by ekinnear** [comment]
Post #26 thoughts: 

- Still generally self-inflicted pain.
- Everything being isolated to within a CONNECT stream means that you're not sharing a pool of available streams anymore.
- You certainly can still read all of the plaintext because... well, you're the one holding the other end of the TLS connection. Given that coalescing requires the cert to be valid for both and otherwise is essentially claiming that they could have been the same "server" (for some value of the word), that seems okay.

@martinthomson anything left to do here? Seems like the architecture change has cleaned up a lot of the potential shared resource concerns quite nicely.

**Comment by martinthomson** [comment]
Yeah, I think we're in pretty good shape now.  Happy to have this closed.

(There are effects that might come from mutual distrust, but those are not any worse than anything else in that situation.)
