### ISSUE TITLE
Describe how to bring up new WebTransport streams without additional roundtrips

### ISSUE THREAD

**Issue by ekinnear** [ietf-wg-webtrans/draft-webtransport-http2#3]
The [overview](https://tools.ietf.org/html/draft-vvv-webtransport-overview-01) contains the following text: 
```
o  Each new stream would require a WebSocket handshake to agree on
      application protocol used, meaning that it would take at least one
      RTT to establish each new stream before the client can write to
      it.
```

We should consider documenting how it's possible to send the connect frame and then the next stream, since we can guarantee in-order delivery (and processing?) of the data.

We can also note that this is orthogonal to 0-RTT.
```
   In some cases, the transport protocol might allow transmitting data
   before the session is established; an example is TLS 0-RTT data.
   Since this data can be replayed by attackers, it MUST NOT be used
   unless the client has explicitly requested 0-RTT for specific streams
   or datagrams it knows to be safely replayable.
```

**Comment by afrind** [comment]
Will this only be possible with WT over H2?  

An HTTP request can be sent at any time over an existing connection, and it contains both information in the headers sufficient to route it to the proper destination AND potentially payload that can be acted upon as soon as it gets there.  Because these are separate streams in HTTP/3, they could arrive out of order at a proxy, which means sending independently routable messages (which require a session and a stream) from H3 have worse latency than H2.  It's also strange because while the browser to edge hop may be H2, subsequent hops may be H3.

**Comment by ekinnear** [comment]
It's possible that this would only work over HTTP/2, which does provide an interesting inversion from the usual benefits that you get from HTTP/3. It would be really nice if these were in a single stream in HTTP/3 as well, but I don't really see that happening if we have CONNECT followed by other streams to which that CONNECT referred.

**Comment by martinthomson** [comment]
I don't think that this is possible with any version of this design, because the client won't have server settings when it sends 0-RTT.  HTTP/2 assumes that default settings are in play, which makes 0-RTT usable for regular requests, but the CONNECT here depends on a setting.

That doesn't seem like it is worth fixing for this mapping.  I also have reservations about the value in making 0-RTT work in the HTTP/3 mapping, but that should be taken up there.

**Comment by afrind** [comment]
This issue says that it is orthogonal to 0-RTT.  It's about sending the CONNECT and one more WT_STREAM/WT_DATAGRAMS in a single flight.  The H3 draft was updated with a section saying this is allowed: https://github.com/ietf-wg-webtrans/draft-ietf-webtrans-http3/blob/main/draft-ietf-webtrans-http3.md#buffering-incoming-streams-and-datagrams.

**Comment by martinthomson** [comment]
Yeah, the h3 draft can allow 0-RTT, but I don't see a way to have the h2 draft do that without taking a dependency on ALPS or some persistent settings concept.  I mean, it could define its own persistent settings concept, but that seems worse than ALPS (and I'm not a big fan, at least for h2).

**Comment by martinthomson** [comment]
Oops, I should have added.  I don't see any reason to allow sending prior to session *confirmation*.  You might, however, allow new streams to be created prior to getting a 200 response on the session.  For that, it really depends on how you might plan to deal with resource management.  Of course, if you could send data inside the primary stream, that makes this largely moot.

**Comment by afrind** [comment]
The H3 draft disallows 0-RTT:

> WebTransport over HTTP/3 does not support 0-RTT.

**Comment by ekinnear** [comment]
Just for clarity, we need to be able to take an already-established WT session and bring up a new stream + get data on that stream in either direction in a single roundtrip, hence the orthogonal-to-0-RTT part.

I think this is now obsolete with #26 since it's pretty clear that a WT_STREAM frame carries data and therefore we don't need to say anything special to make it obvious that this is permitted.
