### ISSUE TITLE
Should SETTINGS_ENABLE_CONNECT_PROTOCOL be sent?

### ISSUE THREAD

**Issue by ddragana** [ietf-wg-webtrans/draft-webtransport-http2#51]
I am afraid that some implementations will oversee the fact that SETTINGS_ENABLE_WEBTRANSPORT actually enables SETTINGS_ENABLE_CONNECT_PROTOCOL and thereby other functionalities, e.g. WebSockets. Therefore it may be better to explicitly send the setting.
This section should also link to https://datatracker.ietf.org/doc/html/draft-ietf-httpbis-h3-websockets-00 and hopefully that draft should have some text about handling the case when a particular extended-connect protocol is not supported.

**Comment by ddragana** [comment]
WebTransport over HTTP/3 has the similar issue.

**Comment by afrind** [comment]
Or perhaps, WebTransport is evolving into something different enough that we don't want to imply support for H2 extended CONNECT for websockets by virtue of supporting webtransport.

**Comment by martinthomson** [comment]
Yeah, I think that - based on discussion about what the setting means - we could reasonably say that supporting extended CONNECT is enough for h2.  For h3, we definitely need the intermediary to signal support.

HOWEVER, an intermediary that fowards HTTP/2 on to HTTP/3 without understanding the protocol contents (which might be possible for *some* extended CONNECT usages, like websockets) will fail fairly spectacularly when it comes to forwarding WebTransport from h2 to h3.  Because we decided that streams and datagrams need to use *real* streams and datagrams in h3.  That comes back to needing a clear signal of support..

UNLESS, if we assume that a server should not ever be in a position to expose an endpoint that speaks WebTransport without ensuring that the resource supports it.  In which case, the error that arises from the h2->h3 forwarding is perfectly OK.

I think that I could live with any outcome here as long as these little wrinkles were properly acknowledged.  I might prefer the minimal approach (no setting for this protocol) if I had to choose.  Adding stuff later is much easier than taking them away.

**Comment by ekinnear** [comment]
Clarifying question about this part, too: 
> This section should also link to https://datatracker.ietf.org/doc/html/draft-ietf-httpbis-h3-websockets-00 and hopefully that draft should have some text about handling the case when a particular extended-connect protocol is not supported.

Wouldn't we have HTTP/3 point to WebSockets over H3, whereas here we'd point to WebSockets over H2?

**Comment by ekinnear** [comment]
Now that we have SETTINGS_MAX_WEBTRANSPORT_SESSIONS in the [DT output](https://github.com/ekinnear/draft-ietf-webtrans-http2/pull/1/files), that should suffice. Keeping this pending that outcome and any updates we want to make for clarity.

**Comment by ekinnear** [comment]
After further discussion, it seems like teaching every layer about every other layer's enablement signals is more painful than originally assumed. Let's keep all the signals.

**Comment by DavidSchinazi** [comment]
Discussed at IETF 115, consensus in room to require all the relevant settings and transport parameters to be sent individually - for this issue means: require that SETTINGS_ENABLE_CONNECT_PROTOCOL be sent
