### ISSUE TITLE
Describe datagram usage

### ISSUE THREAD

**Issue by ekinnear** [ietf-wg-webtrans/draft-webtransport-http2#6]
The [Overview](https://tools.ietf.org/html/draft-vvv-webtransport-overview-01) places requirements on how WebTransport handles datagrams:

```
   The WebTransport sender is not expected to retransmit datagrams,
   though it may if it is using a TCP-based protocol or some other
   underlying protocol that requires reliable delivery.  WebTransport
   datagrams are not expected to be flow controlled, meaning that the
   receiver might drop datagrams if the application is not consuming
   them fast enough.
```

We should describe that Http2Transport is going to retransmit datagrams (being over TCP/TLS/HTTP2) and offer some text about how these interact with flow control.

**Comment by afrind** [comment]
I think the draft also needs to describe what frames will be used to transmit datagrams.  Will that be a new frame type, a single dedicated datagram stream, or a WTHEADERS stream per datagram, etc?

**Comment by ekinnear** [comment]
Agreed, thinking through those three options, a new frame time vs. a dedicated datagram stream don't seem to provide significant differences in practical usage. A new WTHEADERS stream per datagram seems a bit heavyweight given that ordering is going to be enforced whether or not we want that. Are there other advantages to doing so which we'd lose if we didn't go that route?

Putting it in a dedicated datagram stream gives you quite straightforward interactions with flow control and also makes it pretty clear that these are in-order, reliable datagrams regardless of what the application might wish. Haven't thought through all the implications here yet, but it seems like a reasonable approach.

Are there differences in behavior that a new frame type would have beyond just a new datagram stream?

**Comment by ekinnear** [comment]
> quite straightforward interactions with flow control

Although notably, not necessarily what we want, if we want to exempt them from flow control. In theory, as long as we're draining the underlying TLS connection on the other end, that shouldn't be unreasonable since the other endpoint can throw them out if necessary.

**Comment by afrind** [comment]
Here's a strawman for an H2 DATAGRAM frame using the routing stream ID in the frame header:

```
Length(24) | Type(8) = DATAGRAM | 
Flags(8) | 
R | Routing Stream ID (31) |
Pad Len? (8) | 
Payload* |
Padding
```

QUIC DATAGRAM doesn't mention padding, but doesn't need to since padding is a separate frame, but I assume we'd want it here. 

Somewhat related: do we want to continue using routing stream IDs, or switch to using "Session IDs" like h3 webtransport?  I could ask the same question for h3 - since the session is established by a stream, why *not* just use the transport stream ID as the session id?  I have a feeling the answer is "transport streams in session protocol bad".  If we expect WebTransport to be easily gatewayed between h2 and h3, we'd probably want h2 to have a mechanism to convey the session ID (both in datagrams and streams)

**Comment by afrind** [comment]
Regarding

> do we want to continue using routing stream IDs, or switch to using "Session IDs" like h3 webtransport? 

Looks like H3 is replacing session ID with stream ID, so we should keep it as is ;)

https://github.com/vasilvv/webtransport/pull/21

**Comment by afrind** [comment]
I think this can be closed.  The current draft describes how to send datagrams using the WT_DATAGRAM frame, that these frames will be retransmitted (because TCP) and that they are not subject to flow control.
